"""Test multivariate BART components."""

from jax import numpy as jnp
from jax import random
from scipy.stats import chi2, ks_1samp

from bartz.mcmcstep import _sample_wishart_bartlett
from tests.util import assert_close_matrices


class TestWishart:
    """Test the basic properties of the wishart sampler output."""

    def random_pd_matrix(self, key, k):
        """Generate a random positive definite matrix."""
        A = random.normal(key, (k, k))
        return A @ A.T + jnp.eye(k)

    def ill_conditioned_matrix(self, key, k, condition_number=1e6, exact_psd=False):
        """Generate a ill conditioned random positive semi-definite matrix."""
        A = random.normal(key, (k, k))
        U, _ = jnp.linalg.qr(A)

        if exact_psd:
            if k == 1:
                eigs = jnp.array([0.0])
            else:
                smalls = jnp.geomspace(1.0, 1e-6, num=k - 1)
                eigs = jnp.concatenate([smalls, jnp.array([0.0])])
        else:
            eigs = jnp.geomspace(1.0, 1.0 / condition_number, num=k)
        return (U @ jnp.diag(eigs)) @ U.T

    def test_size(self, keys):
        """Check that the sample generated by wishart sampler is of shape k*k."""
        df, k = 5, 3
        scale = self.random_pd_matrix(keys.pop(), k)
        sample = _sample_wishart_bartlett(keys.pop(), df, scale)
        assert sample.shape == (k, k)

    def test_symmetric(self, keys):
        """Check that the sample generated by wishart sampler is symmetric."""
        df, k = 5, 3
        scale = self.random_pd_matrix(keys.pop(), k)
        sample = _sample_wishart_bartlett(keys.pop(), df, scale)
        assert_close_matrices(sample, sample.T, rtol=1e-6)

    def test_pos_def(self, keys):
        """Check that the sample generated by wishart sampler is positive definite."""
        df, k = 5, 3
        scale = self.random_pd_matrix(keys.pop(), k)
        sample = _sample_wishart_bartlett(keys.pop(), df, scale)
        eigs = jnp.linalg.eigvalsh(sample)
        assert jnp.all(eigs > 0)

    def test_near_singular_scale(self, keys):
        """Check that the wishart sampler still works with singular or near singular matrix."""
        df, k = 5, 3
        ill_conditioned_scale = self.ill_conditioned_matrix(keys.pop(), k, 1e6, True)
        sample = _sample_wishart_bartlett(keys.pop(), df, ill_conditioned_scale)
        assert jnp.all(jnp.isfinite(sample))

    def test_wishart_dist(self, keys):
        """Check that the sample generated by wishart sampler follows a wishart distribution."""
        df, k = 5, 3
        nsamples = 100
        sigma = self.random_pd_matrix(keys.pop(), k)
        scale_inv = jnp.linalg.inv(sigma)

        a = random.normal(keys.pop(), (k,))
        denumerator = float(a.T @ sigma @ a)

        ts = []
        for _ in range(nsamples):
            W = _sample_wishart_bartlett(keys.pop(), df, scale_inv)
            t = float(a.T @ W @ a) / denumerator
            ts.append(t)
        ts = jnp.array(ts)

        test = ks_1samp(ts, chi2(df).cdf)
        assert test.pvalue > 0.01
